// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct TestContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for TestContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = TestContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        TestContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct TestContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> TestContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> TestContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn endpoint_0<
        Arg0: ProxyArg<Struct<Env::Api>>,
    >(
        self,
        a: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_0")
            .argument(&a)
            .original_result()
    }

    pub fn endpoint_1(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_1")
            .original_result()
    }

    pub fn endpoint_2<
        Arg0: ProxyArg<u8>,
        Arg1: ProxyArg<u16>,
        Arg2: ProxyArg<u32>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<usize>,
    >(
        self,
        a: Arg0,
        b: Arg1,
        c: Arg2,
        d: Arg3,
        e: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue5<u8, u16, u32, u64, usize>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_2")
            .argument(&a)
            .argument(&b)
            .argument(&c)
            .argument(&d)
            .argument(&e)
            .original_result()
    }

    pub fn endpoint_3<
        Arg0: ProxyArg<i8>,
        Arg1: ProxyArg<i16>,
        Arg2: ProxyArg<i32>,
        Arg3: ProxyArg<i64>,
        Arg4: ProxyArg<isize>,
    >(
        self,
        a: Arg0,
        b: Arg1,
        c: Arg2,
        d: Arg3,
        e: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue5<i8, i16, i32, i64, isize>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_3")
            .argument(&a)
            .argument(&b)
            .argument(&c)
            .argument(&d)
            .argument(&e)
            .original_result()
    }

    pub fn endpoint_4<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        a: Arg0,
        b: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue2<TokenIdentifier<Env::Api>, ManagedAddress<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_4")
            .argument(&a)
            .argument(&b)
            .original_result()
    }

    pub fn endpoint_5<
        Arg0: ProxyArg<Option<TokenIdentifier<Env::Api>>>,
        Arg1: ProxyArg<OptionalValue<u64>>,
    >(
        self,
        a: Arg0,
        b: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue2<Option<TokenIdentifier<Env::Api>>, OptionalValue<u64>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_5")
            .argument(&a)
            .argument(&b)
            .original_result()
    }

    pub fn endpoint_5_bis<
        Arg0: ProxyArg<Option<TokenIdentifier<Env::Api>>>,
        Arg1: ProxyArg<OptionalValue<u64>>,
    >(
        self,
        a: Arg0,
        b: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue2<Option<TokenIdentifier<Env::Api>>, OptionalValue<u64>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_5_bis")
            .argument(&a)
            .argument(&b)
            .original_result()
    }

    pub fn endpoint_6<
        Arg0: ProxyArg<u32>,
        Arg1: ProxyArg<MultiValueEncoded<Env::Api, u32>>,
    >(
        self,
        a: Arg0,
        b: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue2<u32, MultiValueEncoded<Env::Api, u32>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_6")
            .argument(&a)
            .argument(&b)
            .original_result()
    }

    pub fn endpoint_7<
        Arg0: ProxyArg<DayOfWeek>,
        Arg1: ProxyArg<DayOfWeek>,
        Arg2: ProxyArg<EnumWithEverything<Env::Api>>,
        Arg3: ProxyArg<EnumWithEverything<Env::Api>>,
        Arg4: ProxyArg<EnumWithEverything<Env::Api>>,
        Arg5: ProxyArg<EnumWithEverything<Env::Api>>,
    >(
        self,
        a: Arg0,
        b: Arg1,
        c: Arg2,
        d: Arg3,
        e: Arg4,
        f: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue6<DayOfWeek, DayOfWeek, EnumWithEverything<Env::Api>, EnumWithEverything<Env::Api>, EnumWithEverything<Env::Api>, EnumWithEverything<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_7")
            .argument(&a)
            .argument(&b)
            .argument(&c)
            .argument(&d)
            .argument(&e)
            .argument(&f)
            .original_result()
    }

    pub fn endpoint_8<
        Arg0: ProxyArg<MultiValueEncoded<Env::Api, EsdtTokenPayment<Env::Api>>>,
    >(
        self,
        payments: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, EsdtTokenPayment<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("endpoint_8")
            .argument(&payments)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode)]
pub struct Struct<Api>
where
    Api: ManagedTypeApi,
{
    pub int: u16,
    pub seq: ManagedVec<Api, u8>,
    pub another_byte: u8,
    pub uint_32: u32,
    pub uint_64: u64,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedDecode, NestedEncode)]
pub enum DayOfWeek {
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
    Sunday,
}

#[rustfmt::skip]
#[type_abi]
#[derive(TopEncode, TopDecode)]
pub enum EnumWithEverything<Api>
where
    Api: ManagedTypeApi,
{
    Default,
    Today(DayOfWeek),
    Write(ManagedVec<Api, u8>, u16),
    Struct {
        int: u16,
        seq: ManagedVec<Api, u8>,
        another_byte: u8,
        uint_32: u32,
        uint_64: u64,
    },
}
